import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    let i = 0;
    setInterval(() => {
      setProgress(i);
      i += 1;
    }, 500);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="outer-circle"
        style={{
          background: `conic-gradient(red ${progress}deg, blue ${progress}deg)`,
        }}
      >
        <div className="inner-circle"></div>
      </div>
    </div>
  );
};

export default Home;
