import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useMemo, useEffect } from "react";

const Home: NextPage = () => {
  const [seconds, setSeconds] = useState(0);
  const [miliseconds, setMiliSeconds] = useState(0);
  const [timeLimit, setTimeLimit] = useState(1);
  const [time, setTime] = useState(`${timeLimit}:00`);

  function updateTime(time: string) {
    let [minutes, seconds] = time.split(":").map((str) => Number(str));
    seconds -= 1;
    if (seconds < 0) {
      [minutes, seconds] = minutes === 0 ? [0, 0] : [minutes - 1, 59];
    }
    if (seconds < 10) return `${minutes}:0${seconds}`;
    return `${minutes}:${seconds}`;
  }

  function calculateProgress(iterator: number, minutes: number) {
    return (360 * ((iterator + 1) / (minutes * 60))) / 10;
  }

  useEffect(() => {
    let i = 0;
    let interval = setInterval(() => {
      if (timeLimit * 60 === i / 10) return clearInterval(interval);
      if (i % 10 === 0) setSeconds((i + 1) / 10);
      setMiliSeconds(i + 1);
      i += 1;
    }, 100);
  }, []);

  useEffect(() => {
    let new_time = updateTime(time);
    setTime(new_time);
  }, [seconds]);

  let progress = useMemo(
    () => calculateProgress(miliseconds, timeLimit),
    [miliseconds]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="outer-circle"
        style={{
          background: `conic-gradient(red ${progress}deg, blue ${progress}deg)`,
        }}
      >
        <div className="inner-circle">
          <time className="time" dateTime="{time}">
            {time}
          </time>
        </div>
      </div>
    </div>
  );
};

export default Home;
